<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVNegucK\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVNegucK/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerVNegucK.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerVNegucK\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerVNegucK\appAppKernelProdContainer([
    'container.build_hash' => 'VNegucK',
    'container.build_id' => 'b38f8108',
    'container.build_time' => 1674357002,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVNegucK');
