<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLMyHrOI\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLMyHrOI/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerLMyHrOI.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerLMyHrOI\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerLMyHrOI\appAppKernelProdContainer([
    'container.build_hash' => 'LMyHrOI',
    'container.build_id' => '15324f3f',
    'container.build_time' => 1674311389,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLMyHrOI');
